### ISSUE TITLE
a small bug

### ISSUE THREAD

**Issue by lilili87222** [blacktop/go-macho#20]
objc.go  line  1407 	 
```
//this code caused all CFString64T of the return value the same value
cfstrings[idx].CFString64T =&cfstr 
```

change  to follow to fix

`cfstrings[idx].CFString64T =&cfStrTypes[idx];// &cfstr`

**Comment by blacktop** [comment]
Do you have a binary example that exhibits this behavior?

**Comment by lilili87222** [comment]
any macho file.this a common problem of go loop

**Comment by blacktop** [comment]
ah I see what you mean now, I never used/looked that that data because I also create the higher order data of the Name and Address fields which WOULD be correct.  I think I wanted to use the pointer so that I wouldn't create 2 copies of the data, but I think it makes more sense to just not use a pointer and then it can be:
`cfstrings[idx].CFString64T =cfstr` what do you think?

**Comment by lilili87222** [comment]
It works well now
